### ISSUE TITLE
NeatFlix

### ISSUE THREAD

**Issue by junaidr638** [Ericgacoki/NeatFlix#19] opened 2023-02-20 00:39 UTC

**Comment by Ericgacoki** [comment] 2023-02-20 10:48
@junaidr638 what's the issue?

**Comment by Ericgacoki** [comment] 2023-02-21 09:09
I think i can relate based on the issue title. Yeah, the app naming was a bit messed up. First started with NeatFlix then NeatFreaks and back to NeatFlix. All this drama was caused by Google Play Store that ended up blocking my account anyways.

The app name has now been reinstated to **NeatFlix** in all packages within the app.

**Comment by Ericgacoki** [comment] 2023-02-21 09:10
Marking as resolved

**Closed by Ericgacoki** 2023-02-21 09:10 UTC
